name: Create .zip
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Prepare files to archive
        run: |
          mkdir -p root/rel/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: root
          file_path: root.zip
          verbose: true

