name: Zip Files

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip Files
      run: |
        zip latest.zip background.js manifest.json
