name: Create .zip
on: push
jobs:
  compress:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2
      - name: Prepare files to archive
        run: |
          mkdir -p latest/rel/
          cp content.js latest/rel
          cp manifest.json latest/rel
          
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: latest
          file_path: latest.zip
          verbose: true

