name: Zip Files and Upload as Artifact

on:
  push:
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip Files
      run: zip archive_name.zip background.js manifest.json

    - name: Upload Zip as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: savespot.zip
        path: savespot.zip
